version: 2
updates:
    - package-ecosystem: 'npm'
      directory: '/'
      schedule:
          interval: 'daily'
      open-pull-requests-limit: 1
      groups:
          eslint:
              patterns:
                  - '*eslint*'
              exclude-patterns:
                  - '*prettier*'
          prettier:
              patterns:
                  - '*prettier*'
          jest:
              patterns:
                  - '*jest*'
          react:
              patterns:
                  - '*react*'
    - package-ecosystem: 'github-actions'
      directory: '/'
      schedule:
          interval: 'weekly'
      open-pull-requests-limit: 1
